
package hu.vanio.springwsmtom.wstypes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "contentStoreHttpPort", targetNamespace = "http://www.springframework.org/spring-ws/samples/mtom")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContentStoreHttpPort {


    /**
     * 
     * @param storeContentRequest
     * @return
     *     returns hu.vanio.springwsmtom.wstypes.StoreContentResponse
     */
    @WebMethod(operationName = "StoreContent")
    @WebResult(name = "StoreContentResponse", targetNamespace = "http://www.springframework.org/spring-ws/samples/mtom", partName = "StoreContentResponse")
    public StoreContentResponse storeContent(
        @WebParam(name = "StoreContentRequest", targetNamespace = "http://www.springframework.org/spring-ws/samples/mtom", partName = "StoreContentRequest")
        StoreContentRequest storeContentRequest);

    /**
     * 
     * @param loadContentRequest
     * @return
     *     returns hu.vanio.springwsmtom.wstypes.LoadContentResponse
     */
    @WebMethod(operationName = "LoadContent")
    @WebResult(name = "LoadContentResponse", targetNamespace = "http://www.springframework.org/spring-ws/samples/mtom", partName = "LoadContentResponse")
    public LoadContentResponse loadContent(
        @WebParam(name = "LoadContentRequest", targetNamespace = "http://www.springframework.org/spring-ws/samples/mtom", partName = "LoadContentRequest")
        LoadContentRequest loadContentRequest);

}
