//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.28 at 09:08:28 PM IST 
//


package springws.usecase.generatedClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the springws.usecase.generatedClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: springws.usecase.generatedClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StoreContentRequest }
     * 
     */
    public StoreContentRequest createStoreContentRequest() {
        return new StoreContentRequest();
    }

    /**
     * Create an instance of {@link StoreContentResponse }
     * 
     */
    public StoreContentResponse createStoreContentResponse() {
        return new StoreContentResponse();
    }

    /**
     * Create an instance of {@link LoadContentResponse }
     * 
     */
    public LoadContentResponse createLoadContentResponse() {
        return new LoadContentResponse();
    }

    /**
     * Create an instance of {@link LoadContentRequest }
     * 
     */
    public LoadContentRequest createLoadContentRequest() {
        return new LoadContentRequest();
    }

}
